import streamlit as st
from components.theme import disclaimer, metric_strip, panel, section_header
from components.charts import kernel_heatmap

def render():
    section_header("Quantum analysis", "Inspect artifacts generated by the executed quantum-kernel workflow.")
    result = st.session_state.get("experiment_result")
    if not result:
        st.info("Run an experiment first.")
        return

    q = result["quantum_results"]
    if not q.get("available"):
        st.warning(q.get("reason", "Quantum execution unavailable."))
        st.caption("Install compatible Qiskit dependencies to enable the quantum layer.")
        return

    c = q["configuration"]
    metric_strip([
        ("Backend", c.get("backend", "Qiskit simulator")),
        ("Feature map", c["feature_map"].upper()),
        ("Qubits", c["num_qubits"]),
        ("Train samples", c["train_samples"]),
        ("Kernel alignment", f'{q["kernel_target_alignment"]:.3f}'),
    ])

    with panel("Quantum circuit"):
        st.code(q["circuit"], language="text")

    with panel("Kernel similarity matrix"):
        st.plotly_chart(kernel_heatmap(q["kernel_preview"]))

    with panel("Kernel diagnostics"):
        st.json(q["kernel_diagnostics"])

    st.caption(
        "This MVP uses a bounded simulator-backed fidelity kernel. Hardware "
        "execution, quantum advantage, and clinical benefit are not established."
    )

    disclaimer("This page displays artifacts generated by the executed quantum experiment, not a decorative conceptual circuit.")
