import streamlit as st
from components.theme import disclaimer, metric_strip, panel, section_header
from components.charts import kernel_heatmap
from services.comparison_service import get_quantum_vs_classical_summary

def render():
    section_header("Quantum analysis", "Inspect artifacts generated by the executed quantum-kernel workflow.")
    result = st.session_state.get("experiment_result")
    if not result:
        st.info("Run an experiment first.")
        return

    q = result["quantum_results"]
    if not q.get("available"):
        st.warning(q.get("reason", "Quantum execution unavailable."))
        st.caption("Install compatible Qiskit dependencies to enable the quantum layer.")
        return

    c = q["configuration"]
    metric_strip([
        ("Backend", c.get("backend", "Qiskit simulator")),
        ("Feature map", c["feature_map"].upper()),
        ("Qubits", c["num_qubits"]),
        ("Train samples", c["train_samples"]),
        ("Kernel alignment", f'{q["kernel_target_alignment"]:.3f}'),
    ])

    # Show quantum vs classical comparison
    quantum_summary = get_quantum_vs_classical_summary(result)
    if quantum_summary.get("status") == "completed":
        st.subheader("Quantum vs Classical Performance")
        q_vs_c = quantum_summary["quantum_vs_best_classical"]
        
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric(
                "Best Classical",
                f"{q_vs_c['classical_accuracy']:.1%}",
                label_visibility="visible"
            )
        with col2:
            st.metric(
                "Quantum",
                f"{q_vs_c['quantum_accuracy']:.1%}",
                delta=f"{q_vs_c['accuracy_delta']:+.1%}",
                label_visibility="visible"
            )
        with col3:
            st.metric(
                "Quantum F1",
                f"{q_vs_c['quantum_f1']:.4f}",
                label_visibility="visible"
            )
        with col4:
            st.metric(
                "Quantum ROC-AUC",
                f"{q_vs_c['quantum_roc_auc']:.4f}",
                label_visibility="visible"
            )
        
        st.caption(
            f"Classical: {q_vs_c['classical_model']} (stratified 5-fold CV). "
            f"Quantum: holdout validation. Note: Different protocols; see Benchmark page for full comparison."
        )

    with panel("Quantum circuit"):
        st.code(q["circuit"], language="text")

    with panel("Kernel similarity matrix"):
        st.plotly_chart(kernel_heatmap(q["kernel_preview"]))
        st.caption("Brighter cells indicate higher simulated feature-map similarity between bounded quantum-kernel samples.")

    with panel("Kernel diagnostics"):
        st.json(q["kernel_diagnostics"])

    st.info(
        "This experiment evaluates a quantum kernel on a bounded simulator. "
        "Results show how a quantum-enhanced learning approach performs on this specific dataset. "
        "Classical baselines remain available for fair comparison on the Benchmark page."
    )

    st.caption(
        "This MVP uses a bounded simulator-backed fidelity kernel. Hardware "
        "execution, quantum advantage, and clinical benefit are not established."
    )

    disclaimer("This page displays artifacts generated by the executed quantum experiment, not a decorative conceptual circuit.")
